name: saafapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  universal_html: ^2.2.4
  path_provider: ^2.1.2
  share_plus: ^7.2.2

  # ðŸ—ºï¸ Ø§Ù„Ø®Ø±Ø§Ø¦Ø· ÙˆØ§Ù„Ù…ÙˆÙ‚Ø¹
  http: ^1.1.0
  google_maps_flutter: ^2.6.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  animate_do: ^4.2.0
  curved_navigation_bar: ^1.0.6

  # ðŸŒ Ø§Ù„Ø®Ø·ÙˆØ· ÙˆØ§Ù„ØªØµÙ…ÙŠÙ…
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.1
  cupertino_icons: ^1.0.8

  # ðŸ“¸ Ø§Ù„ØµÙˆØ±Ø© ÙˆØ§Ù„ØµÙˆØª
  image_picker: ^1.2.0
  audioplayers: ^6.5.1

  # ðŸ”¥ Firebase (Ø¥ØµØ¯Ø§Ø±Ø§Øª Ù…ØªÙˆØ§ÙÙ‚Ø© Ù…Ø¹ Flutter 3.9)
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.2.10

  # Ø­Ù„ ØªØ¹Ø§Ø±Ø¶ geolocator_web â†’ web
  # web: ^1.1.1
  flutter_dotenv: ^6.0.0
  firebase_app_check: ^0.3.2+10

  # ðŸŽžï¸ Ø§Ù†ÙŠÙ…ÙŠØ´Ù† Ù„ÙˆØªÙŠ
  lottie: ^3.1.2

  uuid: ^4.5.1
  zxcvbn: ^1.0.0
  video_player: ^2.10.1
  fl_chart: ^1.1.1
  flutter_map: ^8.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Appicon.png
  adaptive_icon_background: "#042c25"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/palms.jpg
    - assets/images/saaf_logo.png
    - assets/audio/palm_breeze.mp3
    - assets/images/about1.png
    - assets/images/about2.png
    - assets/images/about3.png
    - assets/gif/loading.gif

    

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
